# Generated by Django 3.0.5 on 2024-03-17 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couriermanage', '0025_auto_20231205_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='sender_phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
